apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2018-03-03T21:53:42Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-aggregator
  resourceVersion: "51"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/system%3Akube-aggregator
  uid: 56e0532b-1f2d-11e8-9d56-029b95027374
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
