apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2018-03-03T21:53:42Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:horizontal-pod-autoscaler
  resourceVersion: "67"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/system%3Acontroller%3Ahorizontal-pod-autoscaler
  uid: 56f486d0-1f2d-11e8-9d56-029b95027374
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - update
- apiGroups:
  - '*'
  resources:
  - '*/scale'
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resourceNames:
  - 'http:heapster:'
  - 'https:heapster:'
  resources:
  - services/proxy
  verbs:
  - get
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
