apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2018-03-03T21:53:43Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:resourcequota-controller
  resourceVersion: "107"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/system%3Acontroller%3Aresourcequota-controller
  uid: 5745b2de-1f2d-11e8-9d56-029b95027374
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:resourcequota-controller
subjects:
- kind: ServiceAccount
  name: resourcequota-controller
  namespace: kube-system
